# Generated by Django 3.1.6 on 2021-02-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201223_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='follows',
        ),
    ]
