# Generated by Django 3.1.6 on 2021-02-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_follow_is_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_like',
        ),
    ]
