# Generated by Django 3.1.3 on 2021-03-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210224_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_private_account',
            field=models.BooleanField(default=False),
        ),
    ]
